#pragma once
#include <filesystem>
#include <string>
#include <string_view>

namespace hbfsim::app {
std::filesystem::path default_hbf_wear_prefix();
// The snapshot is generated by HbfController, including zero-erase workloads.
void write_hbf_wear_report(const std::filesystem::path& prefix, std::string_view snapshot);
} // namespace hbfsim::app
